<?php
$action = $this->getAction();
if(!isset($_SESSION))
{
    session_start();
}

?>


<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link href="/css/style.css" rel="stylesheet" media="all" >

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/home/index">Pizza shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/home/index">home/menu

                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/cart">Cart

                </a>
            </li>
            <?php
            if(!isset($_SESSION['email'])){
                echo "
                 <li class=\"nav-item active\">
                <a class=\"nav-link\" href=\"/user/registration\">Registration</a>
            </li>
            <li class=\"nav-item active\">
                <a class=\"nav-link\" href=\"/user/login\">Log in</a>
            </li>
            ";
            }else{
                echo "
            <li class=\"nav-item active\">
                <a class=\"nav-link\"  onclick=\"myFunction()\">logout</a>
            </li>
            ";
            }
            ?>
            <li class="nav-item active">
                <a class="nav-link" href="/admin/index">Admin</a>
            </li>
        </ul>
    </div>
</nav>
</body>

